FROM python:3.8

WORKDIR /app
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install --no-cache-dir nvflare numpy itk-io monai pandas kaleido plotly torch torchvision protobuf==3.20

#RUN pip install --no-cache-dir nvflare

#python -m virtualenv nvflare
#source nvflare/bin/activate
#pip install -U pip
#pip install nvflare
#cd nvflare 
#mkdir demo
#yes y | poc -n 2 
#cd poc/server/startup
#./start.sh
 


#COPY src /app

#CMD [ "python", "server.py" ]

